### ISSUE TITLE
Separate your *.js and *.coffee files

### ISSUE THREAD

**Issue by indexzero** [dan-manges/m2node#1]
Very cool library! Looking forward to checking it out. I'm not a huge coffeescript user, but it's become somewhat conventional to separate `*.js` and `*.coffee` files during your compilation process. 

Usually something like:

```
  /lib
    *.coffee
  /src
    *.js
```

Take it with a grain of salt I suppose.

**Comment by dan-manges** [comment]
Thanks for the feedback Charlie. I looked into it a little bit and it seemed like the convention was to put coffee files in src and js files in lib, so I split them that way.

**Comment by indexzero** [comment]
Cool. I always get that mixed up. Good stuff, looking forward to playing with this.
