### ISSUE TITLE
zeromq -> zmq for dependencies

### ISSUE THREAD

**Issue by itsnotvalid** [dan-manges/m2node#5]
The name of that package is changed to zmq.
Reference:
https://github.com/JustinTulloss/zeromq.node/commit/9e0b7411503d29e419a2cb0fe9001628ff8d660f

**Comment by dan-manges** [comment]
Thanks for reporting this. I'll update this and pull in other patches and released an updated version of m2node today.

**Comment by dan-manges** [comment]
Fixed in commit 96d8e7030
